-- $ sqlite3 ./var/api.db < ./share/api.sql

PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS Users (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Games (
  GameId INTEGER PRIMARY KEY AUTOINCREMENT,
  UserId INTEGER NOT NULL,
  Word TEXT NOT NULL,
  MovesCompleted INTEGER DEFAULT 0,
  GameCompleted INTEGER DEFAULT 0,
  FOREIGN KEY(Word) REFERENCES Words(Word),
  FOREIGN KEY(UserId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS Guesses (
  GuessId INTEGER PRIMARY KEY AUTOINCREMENT,
  GameId INTEGER NOT NULL,
  Guess TEXT NOT NULL,
  Hint TEXT NOT NULL,
  FOREIGN KEY(GameId) REFERENCES Games(GameId)
);

CREATE TABLE IF NOT EXISTS Words (
  Word TEXT PRIMARY KEY,
  Correct INTEGER NOT NULL
);

COMMIT;